### ISSUE TITLE
Finalize form fields/descriptions

### ISSUE THREAD

**Issue by gfkang** [CMU-313/fall-2021-hw2-team-name#12]
Basic form created in 2ec5efd9993aada95c75b81f8f6594eda524db33. Finalize form fields before moving on to integration and database interaction.

**Comment by dsduenas** [comment]
Add a text field for additional comments.

**Comment by gfkang** [comment]
It would be good to have a field describing the reviewer's decision for the candidate. We could either do a yes/no dropdown or a rating like 1/5.

**Comment by dsduenas** [comment]
If we add fields for undergraduate education, the degree they are pursuing, extracurriculars, an upload button for letters of recommendation as well that should be enough fields for the finalized form.

**Comment by dsduenas** [comment]
The final form fields are

- First Name
- Last Name
- Email Address
- Experience Score
- Skills Score
- GPA
- Essay Score
- Additional Comments
- Final Decision
- Name of the Reviewer
